# Powerlevel10k sleek lean prompt configuration for Agent Terminal
'builtin' 'local' '-a' 'p10k_config_opts'
'builtin' 'local' '-h' 'POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS'
'builtin' 'local' '-h' 'POWERLEVEL9K_LEFT_PROMPT_ELEMENTS'

# Left prompt elements (Clean & readable)
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
  dir                     # current working directory
  vcs                     # git status
  prompt_char             # prompt symbol ❯
)

# Right prompt elements (Minimalist, no ugly user@hostname boxes)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
  status                  # exit code
  command_execution_time  # duration
)

POWERLEVEL9K_MODE='nerdfont-v3'
POWERLEVEL9K_ICON_PADDING=none
POWERLEVEL9K_PROMPT_ADD_NEWLINE=false
POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX=''
POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX=''

# Directory styling - Transparent background, vibrant cyan text
POWERLEVEL9K_DIR_BACKGROUND='none'
POWERLEVEL9K_DIR_FOREGROUND='cyan'
POWERLEVEL9K_DIR_SHORTENED_FOREGROUND='cyan'
POWERLEVEL9K_DIR_ANCHOR_FOREGROUND='cyan'
POWERLEVEL9K_DIR_ANCHOR_BOLD=true
POWERLEVEL9K_SHORTEN_STRATEGY='truncate_to_unique'

# VCS (Git) styling - Transparent background, green text
POWERLEVEL9K_VCS_BACKGROUND='none'
POWERLEVEL9K_VCS_CLEAN_FOREGROUND='green'
POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_MODIFIED_FOREGROUND='yellow'
POWERLEVEL9K_VCS_LOADING_TEXT='fetching...'

# Prompt character styling (❯)
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_FOREGROUND='green'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_FOREGROUND='red'
POWERLEVEL9K_PROMPT_CHAR_OK_VIINS_CONTENT_EXPANSION='❯'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VIINS_CONTENT_EXPANSION='❯'
POWERLEVEL9K_PROMPT_CHAR_OK_VICMD_CONTENT_EXPANSION='❮'
POWERLEVEL9K_PROMPT_CHAR_ERROR_VICMD_CONTENT_EXPANSION='❮'

# Execution time styling
POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND='none'
POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND='yellow'

# Status styling
POWERLEVEL9K_STATUS_BACKGROUND='none'
POWERLEVEL9K_STATUS_OK=false
POWERLEVEL9K_STATUS_ERROR_FOREGROUND='red'
